### ISSUE TITLE
Could not transfer artifact wolfendale:scalacheck-gen-regexp_2.12:pom:0.1.2 from/to central

### ISSUE THREAD

**Issue by ChiuWeiBin** [etspaceman/scalacheck-faker#102]
I got this error when building the MAVEN project
Error:

`Could not transfer artifact wolfendale:scalacheck-gen-regexp_2.12:pom:0.1.2 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/wolfendale/scalacheck-gen-regexp_2.12/0.1.2/scalacheck-gen-regexp_2.12-0.1.2.pom`

Any workaround?

**Comment by ChiuWeiBin** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.wbchiu</groupId>
  <artifactId>com.test</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <encoding>UTF-8</encoding>

    <gatling.version>3.3.1</gatling.version>
    <gatling-maven-plugin.version>3.0.5</gatling-maven-plugin.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.gatling.highcharts</groupId>
      <artifactId>gatling-charts-highcharts</artifactId>
      <version>${gatling.version}</version>
    </dependency>
    <dependency>
      <groupId>io.gatling</groupId>
      <artifactId>gatling-app</artifactId>
      <version>${gatling.version}</version>
    </dependency>
    <dependency>
      <groupId>io.gatling</groupId>
      <artifactId>gatling-recorder</artifactId>
      <version>${gatling.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.etspaceman</groupId>
      <artifactId>scalacheck-faker_2.12</artifactId>
      <version>5.0.10</version>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>io.gatling</groupId>
        <artifactId>gatling-maven-plugin</artifactId>
        <version>${gatling-maven-plugin.version}</version>
      </plugin>
    </plugins>
  </build>
</project>

```

**Comment by etspaceman** [comment]
Hello - 

This dependency is provided on bintray. My SBT build had to include an extra resolver, see:

https://github.com/etspaceman/scalacheck-faker/blob/master/build.sbt#L23

https://bintray.com/wolfendale/maven/scalacheck-gen-regexp/0.1.2

**Comment by ChiuWeiBin** [comment]
Hi @etspaceman ,

I am still getting error. Am I doing something wrong here?

`Could not transfer artifact wolfendale:scalacheck-gen-regexp_2.12:pom:0.1.2 from/to bintray-wolfendale-maven (https://dl.bintray.com/wolfendale/maven): Transfer failed for https://dl.bintray.com/wolfendale/maven/wolfendale/scalacheck-gen-regexp_2.12/0.1.2/scalacheck-gen-regexp_2.12-0.1.2.pom
`

**POM.xml**


<?xml version="1.0" encoding="UTF-8"?>


    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <encoding>UTF-8</encoding>

        <gatling.version>3.3.1</gatling.version>
        <gatling-maven-plugin.version>3.0.5</gatling-maven-plugin.version>
    </properties>


    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-wolfendale-maven</id>
            <name>bintray</name>
            <url>https://dl.bintray.com/wolfendale/maven</url>
        </repository>
    </repositories>


    <dependencies>
        <dependency>
            <groupId>io.gatling.highcharts</groupId>
            <artifactId>gatling-charts-highcharts</artifactId>
            <version>${gatling.version}</version>
        </dependency>
        <dependency>
            <groupId>io.gatling</groupId>
            <artifactId>gatling-app</artifactId>
            <version>${gatling.version}</version>
        </dependency>
        <dependency>
            <groupId>io.gatling</groupId>
            <artifactId>gatling-recorder</artifactId>
            <version>${gatling.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.etspaceman</groupId>
            <artifactId>scalacheck-faker_2.12</artifactId>
            <version>5.0.10</version>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.gatling</groupId>
                <artifactId>gatling-maven-plugin</artifactId>
                <version>${gatling-maven-plugin.version}</version>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by etspaceman** [comment]
The link in the error message works for me (downloaded the POM) so I am not sure. I have not used Maven directly for his work. It might be worth reaching out to the other repository here:

https://github.com/wolfendale/scalacheck-gen-regexp
