### ISSUE TITLE
Add comprehensive documentation

### ISSUE THREAD

**Issue by etspaceman** [etspaceman/scalacheck-faker#13]
Areas include:

- Scaladoc
- GitHub docs

Consider tooling:
- https://scalameta.org/mdoc/
- https://github.com/47degrees/sbt-microsites

**Comment by Slakah** [comment]
If you're interested in some inspiration, I have an open PR https://github.com/alexarchambault/case-app/pull/217 . Hoping to  finish it up when I get some time. Full example used for weaver-test can be seen [here](https://github.com/disneystreaming/weaver-test/commit/7933d01b57441172769fc9dd359d4783a58b39fe) (uses drone to deploy though).

Feel free to reach out, happy to help if that would be useful.

**Comment by etspaceman** [comment]
Thanks for sharing! I will definitely consider this when approaching the documentation. 

> Feel free to reach out, happy to help if that would be useful.

It would be most useful indeed! Please feel free to submit any contributions 😄 . There's a lot of work to do in this repo and I'm only 1 man.
