### ISSUE TITLE
Add company instances

### ISSUE THREAD

**Issue by etspaceman** [etspaceman/scalacheck-faker#3]
See:

- https://github.com/DiUS/java-faker/blob/master/src/main/java/com/github/javafaker/Company.java
- https://github.com/DiUS/java-faker/blob/master/src/main/resources/en/company.yml

**Comment by maheshsv** [comment]
Can I work on this please let me know

**Comment by etspaceman** [comment]
Hey there - I was already working on this but appreciate your eagerness to contribute. Please feel free to submit a pull request in the future with any work that you'd like to contribute.
